function Data = getDataSettings_cyano()
% Data = getDataSettings()
% Returns a structure array that includes the specifications for our data runs.
%
%   Data should be a structure array with the following fields for each data
%   set:
%       - evironment: either 'aerobic' or 'anaerobic'
%       - type: either 'WT' or 'Flg-'
%       - innoculation: date in 'M.D' format; eg '4.27' for April 27th
%       - RunSettings: a cell array where each element is itelf a cell array
%             corresponding to data collected on a particular day for this
%             innoculation. Each of these elements has the following index
%             structure:
%                 (1) The time (in days) since innoculation
%                 (2) The folder the series is located in (by convention, should
%                     be formatted as the date ('M.D') on which it was taken.
%                 (3) A cell array of individual series settings with the
%                     following index structure:
%                         (1) The series number of the stack
%                         (2) The number of initial images to skip
%                         (3) The number of images to use for smacking
%   
%   The format used:
%       Data(n).environment  = 'aerobic' or 'anaerobic';
%       Data(n).type         = 'WT' or 'Flg-';
%       Data(n).innoculation = 'M.D';
%       Data(n).RunSettings  = { {time, folder, { {num, skip, smack} ... } }
%                                .
%                                .
%                                .
%                              }
%       ...
%
%   Usage:
%       DataSettings = getDataSettings()

    Data(1).environment  = Environment.Aerobic;
    Data(1).type         = Type.CyanoWT;
    Data(1).innoculation = '2.25';
    Data(1).Days  = { {7, '3.4', { {10 1 0} {12 0 0} {18 0 0} {22 0 0} } }, ...
                             ...
                             {10, '3.7', { {3 0 0} {7 1 0} {11 1 0} {17 0 0} } }, ...
                             ...
                             {13, '3.10', { {5 1 0} {7 0 0} {9 1 0} {11 10 0} } }, ...
                             ...
                             {14,'3.11',{{2 0 0} {4 1 0} {8 1 0}}}...
                           };
    
    Data(2).environment  = Environment.Aerobic;
    Data(2).type         =  Type.CyanoWT;
    Data(2).innoculation = '3.29';
    Data(2).Days  = { {3, '4.1', { {3 0 0} {5 0 0} {7 1 0} {19 1 0} {21 1 0}...
                                    {23 1 0} {26 1 0} {30 1 0}} }, ...
                             ...
                             {7, '4.5', { {2 1 0} {4 1 0} {13 2 0} } }...
                             ...
                             {10, '4.8', { {69 0 0} {77 1 0} {83 1 0} } }, ...
                           };
                       
    Data(3).environment  = Environment.Aerobic;
    Data(3).type         = Type.CyanoMotile;
    Data(3).innoculation = '3.29';
    Data(3).Days  = { {3, '4.1',  { {34 1 0} {41 1 0} {45 1 0} {49 1 0} {51 1 0}...
                                    {53 1 0} } }, ...
                             ...
                             {7, '4.5',   { {18 2 0} {24 1 0} {30 1 0} {34 1 0} ...
                                {40 0 0} {46 1 0} {48 2 0} {50 0 0} {57 0 0} {59 0 0}} }, ...
                             ...
                             {10, '4.8',   { {87 0 0} {99 1 0} {109 1 0} } }, ...
                           };
                       
    Data(4).environment  = Environment.Aerobic;
    Data(4).type         =  Type.CyanoWT;
    Data(4).innoculation = '4.11';
    Data(4).Days  = { {2, '4.13',  { {28 21 0} {32 16 0} {34 18 0} {36 15 0}...
                            {38 23 0} {42 26 0} {45 12 0} {47 0 0} {49 1 0} {51 1 0}} }, ...
                             ...
                             {4, '4.15',   { {11 2 0} {15 0 0} {20 1 0} {30 1 0} } }, ...
                             ...
                             {7, '4.20',   { {43 0 0} {48 0 0} } }, ...
                           };
                       
   
end